### ISSUE TITLE
Not working right now

### ISSUE THREAD

**Issue by StixUnite23** [w3bOs/DBFG#1]
It is not doing anything at the moment

**Comment by ciberweaboo** [comment]
> It is not doing anything at the moment

you use pc or android?

you installed it properly?

any console issue?

**Comment by w3bOs** [comment]
...

**Comment by w3bOs** [comment]
...

**Comment by StixUnite23** [comment]
The modification doesn't activate when you turn it on and says there is an
error

**Comment by StixUnite23** [comment]
I use the android version of the mod, the modification doesn't activate and says there are errors when I try to turn it off and back on, and when it does activate and I go to the store, everything is still the same as if the mod isn't even there, and I made sure it was installed correctly.
